# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Proyek Sains Data IF 5B
author: Muhammad Ainul Fuady
logo: logo.jpg
copyright: "2026"

# Re-use cached notebook outputs; don't force re-execution on every build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  # Don't execute working notebooks that need an openEO login / long batch jobs.
  
# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/muhammadainulfuady/PSD
  path_to_book: .
  branch: main

# Add GitHub buttons to your book
html:
  use_issues_button: true
  use_repository_button: true
  extra_css:
    - _static/custom.css
